# -*- coding: utf-8 -*-
"""confusion_matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gcsNUKX_g8ESyteKKsPcJio7j04it5QM
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.special import softmax
from sklearn.metrics import classification_report
import ast
import os

#

# inputs
import joblib
import argparse

# Parse command-line arguments for file paths
parser = argparse.ArgumentParser(description="Generate side-by-side bar plots for actual vs predicted labels.")
parser.add_argument("--preds_base_path", type=str, required=True, help="Path to the saved PredictionOutput (pickle file).")
parser.add_argument("--preds_proposed_path", type=str, required=True, help="Path to the saved tokenized dataset (pickle file).")
args = parser.parse_args()

# Load objects
preds_inp = joblib.load(args.preds_base_path)
preds_proposed_inp = joblib.load(args.preds_proposed_path)


# Create an EDA folder if it doesn't exist
def create_eda_folder():
    current_dir = os.getcwd()

    eda_folder_path = os.path.join(current_dir, 'EDA')
    if not os.path.exists(eda_folder_path):
        os.makedirs(eda_folder_path)

def report(preds):

    # probs and class assignments

    y_true = preds.label_ids
    y_pred = np.argmax(preds.predictions, axis=-1)

    label_names = set(preds.label_ids.tolist())
    report = classification_report(y_true, y_pred, target_names=label_names, output_dict=True)
    report_df = pd.DataFrame(report).round(2).reset_index()

    return report_df

# this function converts a dataframe (pandas) to a graph of that df (as a picture)
def render_mpl_table(data, col_width=3.0, row_height=0.625, font_size=14,
                     header_color='#40466e', row_colors=['#f1f1f2', 'w'], edge_color='w',
                     bbox=[0, 0, 1, 1], header_columns=0,
                     ax=None, **kwargs):
    if ax is None:
        size = (np.array(data.shape[::-1]) + np.array([0, 1])) * np.array([col_width, row_height])
        fig, ax = plt.subplots(figsize=size)
        ax.axis('off')
    mpl_table = ax.table(cellText=data.values, bbox=bbox, colLabels=data.columns, **kwargs)
    mpl_table.auto_set_font_size(False)
    mpl_table.set_fontsize(font_size)

    for k, cell in mpl_table._cells.items():
        cell.set_edgecolor(edge_color)
        if k[0] == 0 or k[1] < header_columns:
            cell.set_text_props(weight='bold', color='w')
            cell.set_facecolor(header_color)
        else:
            cell.set_facecolor(row_colors[k[0]%len(row_colors) ])
    return ax.get_figure(), ax

#fig,ax = render_mpl_table(df, header_columns=0, col_width=2.0)


def combine_plots():


  # Create side-by-side subplots
  fig, axs = plt.subplots(nrows=2, ncols=1, figsize=(14, 6))
  sns.set(font_scale=1.2)

  # Plot 1: Report for the Base Model
  render_mpl_table(report(preds_inp), header_columns=0, col_width=2.0, ax=axs[0])
  axs[0].set_title("Classification Report for the Base Model")

  # Plot 2: Report for the PEFT Model
  render_mpl_table(report(preds_proposed_inp), header_columns=0, col_width=2.0, ax=axs[1])
  axs[1].set_title("Classification Report for the Proposed Model")


  # Adjust layout
  plt.tight_layout()

create_eda_folder()
plot_to_save = combine_plots()
file_name = 'classification_report_comparison.png'
eda_folder_path = os.path.join(os.getcwd(), 'EDA')


file_path = os.path.join(eda_folder_path, file_name)
#with open(file_path, 'w', encoding = 'utf-8-sig') as f:
plt.savefig(file_path)

text_to_display = 'File name '+file_name[:-4] +'. '+'This is also saved in the EDA folder'
print(text_to_display)
