# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yYHZs5CzDHjS8wbnAGLcPlbEkpNpKKIT
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.special import softmax
import ast
import os
#

# inputs
print("Make sure the output of trainer.predict() is saved as preds and the tokenised dataset as tokenized_datasets as tokenized_datasets")
preds_inp = preds
tokenized_datasets_inp = tokenized_datasets

# preds_inp = input("Paste the name of the predictions table - trainer.predict() output").strip()
# tokenized_datasets_inp = input("Paste the name of tokenized dataset").strip()


# Create an EDA folder if it doesn't exist
def create_eda_folder():
    current_dir = os.getcwd()

    eda_folder_path = os.path.join(current_dir, 'EDA')
    if not os.path.exists(eda_folder_path):
        os.makedirs(eda_folder_path)

def bar_plots(preds, tokenized_datasets):

    # --- Example context before plotting ---
    # probs and class assignments
    probs = softmax(preds.predictions, axis=1)
    predicted_classes = probs.argmax(axis=1)

    #intermediate calcs
    df_temp1 = pd.merge(pd.DataFrame(preds.label_ids).reset_index().rename(columns={0: 'actual_label_ids'}),
                  tokenized_datasets["test"].to_pandas()['text'].reset_index(), right_on='index', left_on= 'index')
    df_temp1 = pd.merge(df_temp1, pd.DataFrame(predicted_classes).reset_index().rename(columns={0: 'predicted_class'}), right_on='index', left_on= 'index')


    # Melt to long format
    df_melted = df_temp1.melt(
        value_vars=['actual_label_ids', 'predicted_class'],
        var_name='type',
        value_name='label'
    )

    # Normalization for percentage plot
    normalized = (
        df_melted
        .groupby(["type", "label"])
        .size()
        .groupby(level=0)
        .apply(lambda x: x / x.sum() * 100)
    )
    normalized.index = normalized.index.droplevel(level=0)
    normalized = normalized.reset_index(name="Percentage")

    # --- Plotting side-by-side ---
    fig, axs = plt.subplots(1, 2, figsize=(12, 5), squeeze=False)
    plt.subplots_adjust(wspace=0.4)

    # Plot 1: Raw counts
    sns.countplot(
        data=df_melted,
        x='label',
        hue='type',
        palette='Set2',
        ax=axs[0, 0]
    )
    axs[0, 0].set_title("Actual vs Predicted Label Counts")
    axs[0, 0].set_xlabel("Label Category", fontsize=10)
    axs[0, 0].set_ylabel("Count", fontsize=10)
    axs[0, 0].legend(title="Type")

    # Plot 2: Normalized (%)
    sns.barplot(
        data=normalized,
        x="label",
        y="Percentage",
        hue="type",
        palette='Set2',
        ax=axs[0, 1]
    )
    axs[0, 1].set_title("Normalized Counts of Actual vs Predicted")
    axs[0, 1].set_xlabel("Label Category", fontsize=10)
    axs[0, 1].set_ylabel("Percentage (%)", fontsize=10)
    axs[0, 1].legend(title="Type")

plot_to_save = bar_plots(preds=preds_inp, tokenized_datasets = tokenized_datasets_inp)
create_eda_folder()
file_name = 'TEST TARGET CLASS: side-by-side (grouped) bar chart.png'
eda_folder_path = os.path.join(os.getcwd(), 'EDA')

file_path = os.path.join(eda_folder_path, file_name)
#with open(file_path, 'w', encoding = 'utf-8-sig') as f:
plt.savefig(file_path)

#plot_to_save
text_to_display = 'File name '+file_name[:-4] +'. '+'This is also saved in the EDA folder'
print(text_to_display)